// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PackRequest.proto

package com.xuanwu.msggate.common.protobuf.pack;

public final class PackRequest {
  private PackRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum PRequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    MESSAGE(0, 0),
    CHANNEL_CHANGE(1, 1),
    BUSINESS_CHANGE(2, 2),
    CANCEL(3, 3),
    ;
    
    public static final int MESSAGE_VALUE = 0;
    public static final int CHANNEL_CHANGE_VALUE = 1;
    public static final int BUSINESS_CHANGE_VALUE = 2;
    public static final int CANCEL_VALUE = 3;
    
    
    public final int getNumber() { return value; }
    
    public static PRequestType valueOf(int value) {
      switch (value) {
        case 0: return MESSAGE;
        case 1: return CHANNEL_CHANGE;
        case 2: return BUSINESS_CHANGE;
        case 3: return CANCEL;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<PRequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PRequestType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PRequestType>() {
            public PRequestType findValueByNumber(int number) {
              return PRequestType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.xuanwu.msggate.common.protobuf.pack.PackRequest.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final PRequestType[] VALUES = {
      MESSAGE, CHANNEL_CHANGE, BUSINESS_CHANGE, CANCEL, 
    };
    
    public static PRequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private PRequestType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.xuanwu.msggate.common.protobuf.pack.PRequestType)
  }
  
  public interface PRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .com.xuanwu.msggate.common.protobuf.UUID packUUID = 1;
    boolean hasPackUUID();
    com.xuanwu.msggate.common.protobuf.CommonItem.UUID getPackUUID();
    com.xuanwu.msggate.common.protobuf.CommonItem.UUIDOrBuilder getPackUUIDOrBuilder();
    
    // required int32 validFrameCount = 2;
    boolean hasValidFrameCount();
    int getValidFrameCount();
    
    // required int64 postTime = 3;
    boolean hasPostTime();
    long getPostTime();
    
    // repeated .com.xuanwu.msggate.common.protobuf.MassFrame massFrames = 4;
    java.util.List<com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame> 
        getMassFramesList();
    com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame getMassFrames(int index);
    int getMassFramesCount();
    java.util.List<? extends com.xuanwu.msggate.common.protobuf.CommonItem.MassFrameOrBuilder> 
        getMassFramesOrBuilderList();
    com.xuanwu.msggate.common.protobuf.CommonItem.MassFrameOrBuilder getMassFramesOrBuilder(
        int index);
    
    // repeated .com.xuanwu.msggate.common.protobuf.GroupFrame groupFrames = 5;
    java.util.List<com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame> 
        getGroupFramesList();
    com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame getGroupFrames(int index);
    int getGroupFramesCount();
    java.util.List<? extends com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrameOrBuilder> 
        getGroupFramesOrBuilderList();
    com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrameOrBuilder getGroupFramesOrBuilder(
        int index);
    
    // optional string attributes = 6;
    boolean hasAttributes();
    String getAttributes();
    
    // optional int32 msgType = 8;
    boolean hasMsgType();
    int getMsgType();
    
    // required .com.xuanwu.msggate.common.protobuf.pack.PRequestType requestType = 7;
    boolean hasRequestType();
    com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequestType getRequestType();
  }
  public static final class PRequest extends
      com.google.protobuf.GeneratedMessage
      implements PRequestOrBuilder {
    // Use PRequest.newBuilder() to construct.
    private PRequest(Builder builder) {
      super(builder);
    }
    private PRequest(boolean noInit) {}
    
    private static final PRequest defaultInstance;
    public static PRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public PRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xuanwu.msggate.common.protobuf.pack.PackRequest.internal_static_com_xuanwu_msggate_common_protobuf_pack_PRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xuanwu.msggate.common.protobuf.pack.PackRequest.internal_static_com_xuanwu_msggate_common_protobuf_pack_PRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .com.xuanwu.msggate.common.protobuf.UUID packUUID = 1;
    public static final int PACKUUID_FIELD_NUMBER = 1;
    private com.xuanwu.msggate.common.protobuf.CommonItem.UUID packUUID_;
    public boolean hasPackUUID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.xuanwu.msggate.common.protobuf.CommonItem.UUID getPackUUID() {
      return packUUID_;
    }
    public com.xuanwu.msggate.common.protobuf.CommonItem.UUIDOrBuilder getPackUUIDOrBuilder() {
      return packUUID_;
    }
    
    // required int32 validFrameCount = 2;
    public static final int VALIDFRAMECOUNT_FIELD_NUMBER = 2;
    private int validFrameCount_;
    public boolean hasValidFrameCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getValidFrameCount() {
      return validFrameCount_;
    }
    
    // required int64 postTime = 3;
    public static final int POSTTIME_FIELD_NUMBER = 3;
    private long postTime_;
    public boolean hasPostTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getPostTime() {
      return postTime_;
    }
    
    // repeated .com.xuanwu.msggate.common.protobuf.MassFrame massFrames = 4;
    public static final int MASSFRAMES_FIELD_NUMBER = 4;
    private java.util.List<com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame> massFrames_;
    public java.util.List<com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame> getMassFramesList() {
      return massFrames_;
    }
    public java.util.List<? extends com.xuanwu.msggate.common.protobuf.CommonItem.MassFrameOrBuilder> 
        getMassFramesOrBuilderList() {
      return massFrames_;
    }
    public int getMassFramesCount() {
      return massFrames_.size();
    }
    public com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame getMassFrames(int index) {
      return massFrames_.get(index);
    }
    public com.xuanwu.msggate.common.protobuf.CommonItem.MassFrameOrBuilder getMassFramesOrBuilder(
        int index) {
      return massFrames_.get(index);
    }
    
    // repeated .com.xuanwu.msggate.common.protobuf.GroupFrame groupFrames = 5;
    public static final int GROUPFRAMES_FIELD_NUMBER = 5;
    private java.util.List<com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame> groupFrames_;
    public java.util.List<com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame> getGroupFramesList() {
      return groupFrames_;
    }
    public java.util.List<? extends com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrameOrBuilder> 
        getGroupFramesOrBuilderList() {
      return groupFrames_;
    }
    public int getGroupFramesCount() {
      return groupFrames_.size();
    }
    public com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame getGroupFrames(int index) {
      return groupFrames_.get(index);
    }
    public com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrameOrBuilder getGroupFramesOrBuilder(
        int index) {
      return groupFrames_.get(index);
    }
    
    // optional string attributes = 6;
    public static final int ATTRIBUTES_FIELD_NUMBER = 6;
    private java.lang.Object attributes_;
    public boolean hasAttributes() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getAttributes() {
      java.lang.Object ref = attributes_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          attributes_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAttributesBytes() {
      java.lang.Object ref = attributes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        attributes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 msgType = 8;
    public static final int MSGTYPE_FIELD_NUMBER = 8;
    private int msgType_;
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getMsgType() {
      return msgType_;
    }
    
    // required .com.xuanwu.msggate.common.protobuf.pack.PRequestType requestType = 7;
    public static final int REQUESTTYPE_FIELD_NUMBER = 7;
    private com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequestType requestType_;
    public boolean hasRequestType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequestType getRequestType() {
      return requestType_;
    }
    
    private void initFields() {
      packUUID_ = com.xuanwu.msggate.common.protobuf.CommonItem.UUID.getDefaultInstance();
      validFrameCount_ = 0;
      postTime_ = 0L;
      massFrames_ = java.util.Collections.emptyList();
      groupFrames_ = java.util.Collections.emptyList();
      attributes_ = "";
      msgType_ = 0;
      requestType_ = com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequestType.MESSAGE;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPackUUID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValidFrameCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPostTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequestType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getPackUUID().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getMassFramesCount(); i++) {
        if (!getMassFrames(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getGroupFramesCount(); i++) {
        if (!getGroupFrames(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, packUUID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, validFrameCount_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, postTime_);
      }
      for (int i = 0; i < massFrames_.size(); i++) {
        output.writeMessage(4, massFrames_.get(i));
      }
      for (int i = 0; i < groupFrames_.size(); i++) {
        output.writeMessage(5, groupFrames_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(6, getAttributesBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeEnum(7, requestType_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(8, msgType_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, packUUID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, validFrameCount_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, postTime_);
      }
      for (int i = 0; i < massFrames_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, massFrames_.get(i));
      }
      for (int i = 0; i < groupFrames_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, groupFrames_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getAttributesBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, requestType_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, msgType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xuanwu.msggate.common.protobuf.pack.PackRequest.internal_static_com_xuanwu_msggate_common_protobuf_pack_PRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xuanwu.msggate.common.protobuf.pack.PackRequest.internal_static_com_xuanwu_msggate_common_protobuf_pack_PRequest_fieldAccessorTable;
      }
      
      // Construct using com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPackUUIDFieldBuilder();
          getMassFramesFieldBuilder();
          getGroupFramesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (packUUIDBuilder_ == null) {
          packUUID_ = com.xuanwu.msggate.common.protobuf.CommonItem.UUID.getDefaultInstance();
        } else {
          packUUIDBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        validFrameCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        postTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (massFramesBuilder_ == null) {
          massFrames_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          massFramesBuilder_.clear();
        }
        if (groupFramesBuilder_ == null) {
          groupFrames_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          groupFramesBuilder_.clear();
        }
        attributes_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        msgType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        requestType_ = com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequestType.MESSAGE;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest.getDescriptor();
      }
      
      public com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest getDefaultInstanceForType() {
        return com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest.getDefaultInstance();
      }
      
      public com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest build() {
        com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest buildPartial() {
        com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest result = new com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (packUUIDBuilder_ == null) {
          result.packUUID_ = packUUID_;
        } else {
          result.packUUID_ = packUUIDBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.validFrameCount_ = validFrameCount_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.postTime_ = postTime_;
        if (massFramesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            massFrames_ = java.util.Collections.unmodifiableList(massFrames_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.massFrames_ = massFrames_;
        } else {
          result.massFrames_ = massFramesBuilder_.build();
        }
        if (groupFramesBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            groupFrames_ = java.util.Collections.unmodifiableList(groupFrames_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.groupFrames_ = groupFrames_;
        } else {
          result.groupFrames_ = groupFramesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000008;
        }
        result.attributes_ = attributes_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000020;
        }
        result.requestType_ = requestType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest) {
          return mergeFrom((com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest other) {
        if (other == com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest.getDefaultInstance()) return this;
        if (other.hasPackUUID()) {
          mergePackUUID(other.getPackUUID());
        }
        if (other.hasValidFrameCount()) {
          setValidFrameCount(other.getValidFrameCount());
        }
        if (other.hasPostTime()) {
          setPostTime(other.getPostTime());
        }
        if (massFramesBuilder_ == null) {
          if (!other.massFrames_.isEmpty()) {
            if (massFrames_.isEmpty()) {
              massFrames_ = other.massFrames_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureMassFramesIsMutable();
              massFrames_.addAll(other.massFrames_);
            }
            onChanged();
          }
        } else {
          if (!other.massFrames_.isEmpty()) {
            if (massFramesBuilder_.isEmpty()) {
              massFramesBuilder_.dispose();
              massFramesBuilder_ = null;
              massFrames_ = other.massFrames_;
              bitField0_ = (bitField0_ & ~0x00000008);
              massFramesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMassFramesFieldBuilder() : null;
            } else {
              massFramesBuilder_.addAllMessages(other.massFrames_);
            }
          }
        }
        if (groupFramesBuilder_ == null) {
          if (!other.groupFrames_.isEmpty()) {
            if (groupFrames_.isEmpty()) {
              groupFrames_ = other.groupFrames_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureGroupFramesIsMutable();
              groupFrames_.addAll(other.groupFrames_);
            }
            onChanged();
          }
        } else {
          if (!other.groupFrames_.isEmpty()) {
            if (groupFramesBuilder_.isEmpty()) {
              groupFramesBuilder_.dispose();
              groupFramesBuilder_ = null;
              groupFrames_ = other.groupFrames_;
              bitField0_ = (bitField0_ & ~0x00000010);
              groupFramesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getGroupFramesFieldBuilder() : null;
            } else {
              groupFramesBuilder_.addAllMessages(other.groupFrames_);
            }
          }
        }
        if (other.hasAttributes()) {
          setAttributes(other.getAttributes());
        }
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasRequestType()) {
          setRequestType(other.getRequestType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPackUUID()) {
          
          return false;
        }
        if (!hasValidFrameCount()) {
          
          return false;
        }
        if (!hasPostTime()) {
          
          return false;
        }
        if (!hasRequestType()) {
          
          return false;
        }
        if (!getPackUUID().isInitialized()) {
          
          return false;
        }
        for (int i = 0; i < getMassFramesCount(); i++) {
          if (!getMassFrames(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getGroupFramesCount(); i++) {
          if (!getGroupFrames(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.xuanwu.msggate.common.protobuf.CommonItem.UUID.Builder subBuilder = com.xuanwu.msggate.common.protobuf.CommonItem.UUID.newBuilder();
              if (hasPackUUID()) {
                subBuilder.mergeFrom(getPackUUID());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPackUUID(subBuilder.buildPartial());
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              validFrameCount_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              postTime_ = input.readInt64();
              break;
            }
            case 34: {
              com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame.Builder subBuilder = com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMassFrames(subBuilder.buildPartial());
              break;
            }
            case 42: {
              com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame.Builder subBuilder = com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addGroupFrames(subBuilder.buildPartial());
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              attributes_ = input.readBytes();
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
              com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequestType value = com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequestType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                bitField0_ |= 0x00000080;
                requestType_ = value;
              }
              break;
            }
            case 64: {
              bitField0_ |= 0x00000040;
              msgType_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .com.xuanwu.msggate.common.protobuf.UUID packUUID = 1;
      private com.xuanwu.msggate.common.protobuf.CommonItem.UUID packUUID_ = com.xuanwu.msggate.common.protobuf.CommonItem.UUID.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.xuanwu.msggate.common.protobuf.CommonItem.UUID, com.xuanwu.msggate.common.protobuf.CommonItem.UUID.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.UUIDOrBuilder> packUUIDBuilder_;
      public boolean hasPackUUID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.UUID getPackUUID() {
        if (packUUIDBuilder_ == null) {
          return packUUID_;
        } else {
          return packUUIDBuilder_.getMessage();
        }
      }
      public Builder setPackUUID(com.xuanwu.msggate.common.protobuf.CommonItem.UUID value) {
        if (packUUIDBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          packUUID_ = value;
          onChanged();
        } else {
          packUUIDBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setPackUUID(
          com.xuanwu.msggate.common.protobuf.CommonItem.UUID.Builder builderForValue) {
        if (packUUIDBuilder_ == null) {
          packUUID_ = builderForValue.build();
          onChanged();
        } else {
          packUUIDBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergePackUUID(com.xuanwu.msggate.common.protobuf.CommonItem.UUID value) {
        if (packUUIDBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              packUUID_ != com.xuanwu.msggate.common.protobuf.CommonItem.UUID.getDefaultInstance()) {
            packUUID_ =
              com.xuanwu.msggate.common.protobuf.CommonItem.UUID.newBuilder(packUUID_).mergeFrom(value).buildPartial();
          } else {
            packUUID_ = value;
          }
          onChanged();
        } else {
          packUUIDBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearPackUUID() {
        if (packUUIDBuilder_ == null) {
          packUUID_ = com.xuanwu.msggate.common.protobuf.CommonItem.UUID.getDefaultInstance();
          onChanged();
        } else {
          packUUIDBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.UUID.Builder getPackUUIDBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPackUUIDFieldBuilder().getBuilder();
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.UUIDOrBuilder getPackUUIDOrBuilder() {
        if (packUUIDBuilder_ != null) {
          return packUUIDBuilder_.getMessageOrBuilder();
        } else {
          return packUUID_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.xuanwu.msggate.common.protobuf.CommonItem.UUID, com.xuanwu.msggate.common.protobuf.CommonItem.UUID.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.UUIDOrBuilder> 
          getPackUUIDFieldBuilder() {
        if (packUUIDBuilder_ == null) {
          packUUIDBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.xuanwu.msggate.common.protobuf.CommonItem.UUID, com.xuanwu.msggate.common.protobuf.CommonItem.UUID.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.UUIDOrBuilder>(
                  packUUID_,
                  getParentForChildren(),
                  isClean());
          packUUID_ = null;
        }
        return packUUIDBuilder_;
      }
      
      // required int32 validFrameCount = 2;
      private int validFrameCount_ ;
      public boolean hasValidFrameCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getValidFrameCount() {
        return validFrameCount_;
      }
      public Builder setValidFrameCount(int value) {
        bitField0_ |= 0x00000002;
        validFrameCount_ = value;
        onChanged();
        return this;
      }
      public Builder clearValidFrameCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        validFrameCount_ = 0;
        onChanged();
        return this;
      }
      
      // required int64 postTime = 3;
      private long postTime_ ;
      public boolean hasPostTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getPostTime() {
        return postTime_;
      }
      public Builder setPostTime(long value) {
        bitField0_ |= 0x00000004;
        postTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearPostTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        postTime_ = 0L;
        onChanged();
        return this;
      }
      
      // repeated .com.xuanwu.msggate.common.protobuf.MassFrame massFrames = 4;
      private java.util.List<com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame> massFrames_ =
        java.util.Collections.emptyList();
      private void ensureMassFramesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          massFrames_ = new java.util.ArrayList<com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame>(massFrames_);
          bitField0_ |= 0x00000008;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame, com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.MassFrameOrBuilder> massFramesBuilder_;
      
      public java.util.List<com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame> getMassFramesList() {
        if (massFramesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(massFrames_);
        } else {
          return massFramesBuilder_.getMessageList();
        }
      }
      public int getMassFramesCount() {
        if (massFramesBuilder_ == null) {
          return massFrames_.size();
        } else {
          return massFramesBuilder_.getCount();
        }
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame getMassFrames(int index) {
        if (massFramesBuilder_ == null) {
          return massFrames_.get(index);
        } else {
          return massFramesBuilder_.getMessage(index);
        }
      }
      public Builder setMassFrames(
          int index, com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame value) {
        if (massFramesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMassFramesIsMutable();
          massFrames_.set(index, value);
          onChanged();
        } else {
          massFramesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setMassFrames(
          int index, com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame.Builder builderForValue) {
        if (massFramesBuilder_ == null) {
          ensureMassFramesIsMutable();
          massFrames_.set(index, builderForValue.build());
          onChanged();
        } else {
          massFramesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addMassFrames(com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame value) {
        if (massFramesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMassFramesIsMutable();
          massFrames_.add(value);
          onChanged();
        } else {
          massFramesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addMassFrames(
          int index, com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame value) {
        if (massFramesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMassFramesIsMutable();
          massFrames_.add(index, value);
          onChanged();
        } else {
          massFramesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addMassFrames(
          com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame.Builder builderForValue) {
        if (massFramesBuilder_ == null) {
          ensureMassFramesIsMutable();
          massFrames_.add(builderForValue.build());
          onChanged();
        } else {
          massFramesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addMassFrames(
          int index, com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame.Builder builderForValue) {
        if (massFramesBuilder_ == null) {
          ensureMassFramesIsMutable();
          massFrames_.add(index, builderForValue.build());
          onChanged();
        } else {
          massFramesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllMassFrames(
          java.lang.Iterable<? extends com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame> values) {
        if (massFramesBuilder_ == null) {
          ensureMassFramesIsMutable();
          super.addAll(values, massFrames_);
          onChanged();
        } else {
          massFramesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearMassFrames() {
        if (massFramesBuilder_ == null) {
          massFrames_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          massFramesBuilder_.clear();
        }
        return this;
      }
      public Builder removeMassFrames(int index) {
        if (massFramesBuilder_ == null) {
          ensureMassFramesIsMutable();
          massFrames_.remove(index);
          onChanged();
        } else {
          massFramesBuilder_.remove(index);
        }
        return this;
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame.Builder getMassFramesBuilder(
          int index) {
        return getMassFramesFieldBuilder().getBuilder(index);
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.MassFrameOrBuilder getMassFramesOrBuilder(
          int index) {
        if (massFramesBuilder_ == null) {
          return massFrames_.get(index);  } else {
          return massFramesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.xuanwu.msggate.common.protobuf.CommonItem.MassFrameOrBuilder> 
           getMassFramesOrBuilderList() {
        if (massFramesBuilder_ != null) {
          return massFramesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(massFrames_);
        }
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame.Builder addMassFramesBuilder() {
        return getMassFramesFieldBuilder().addBuilder(
            com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame.getDefaultInstance());
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame.Builder addMassFramesBuilder(
          int index) {
        return getMassFramesFieldBuilder().addBuilder(
            index, com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame.getDefaultInstance());
      }
      public java.util.List<com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame.Builder> 
           getMassFramesBuilderList() {
        return getMassFramesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame, com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.MassFrameOrBuilder> 
          getMassFramesFieldBuilder() {
        if (massFramesBuilder_ == null) {
          massFramesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame, com.xuanwu.msggate.common.protobuf.CommonItem.MassFrame.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.MassFrameOrBuilder>(
                  massFrames_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          massFrames_ = null;
        }
        return massFramesBuilder_;
      }
      
      // repeated .com.xuanwu.msggate.common.protobuf.GroupFrame groupFrames = 5;
      private java.util.List<com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame> groupFrames_ =
        java.util.Collections.emptyList();
      private void ensureGroupFramesIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          groupFrames_ = new java.util.ArrayList<com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame>(groupFrames_);
          bitField0_ |= 0x00000010;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame, com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrameOrBuilder> groupFramesBuilder_;
      
      public java.util.List<com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame> getGroupFramesList() {
        if (groupFramesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(groupFrames_);
        } else {
          return groupFramesBuilder_.getMessageList();
        }
      }
      public int getGroupFramesCount() {
        if (groupFramesBuilder_ == null) {
          return groupFrames_.size();
        } else {
          return groupFramesBuilder_.getCount();
        }
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame getGroupFrames(int index) {
        if (groupFramesBuilder_ == null) {
          return groupFrames_.get(index);
        } else {
          return groupFramesBuilder_.getMessage(index);
        }
      }
      public Builder setGroupFrames(
          int index, com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame value) {
        if (groupFramesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGroupFramesIsMutable();
          groupFrames_.set(index, value);
          onChanged();
        } else {
          groupFramesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setGroupFrames(
          int index, com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame.Builder builderForValue) {
        if (groupFramesBuilder_ == null) {
          ensureGroupFramesIsMutable();
          groupFrames_.set(index, builderForValue.build());
          onChanged();
        } else {
          groupFramesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addGroupFrames(com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame value) {
        if (groupFramesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGroupFramesIsMutable();
          groupFrames_.add(value);
          onChanged();
        } else {
          groupFramesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addGroupFrames(
          int index, com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame value) {
        if (groupFramesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGroupFramesIsMutable();
          groupFrames_.add(index, value);
          onChanged();
        } else {
          groupFramesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addGroupFrames(
          com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame.Builder builderForValue) {
        if (groupFramesBuilder_ == null) {
          ensureGroupFramesIsMutable();
          groupFrames_.add(builderForValue.build());
          onChanged();
        } else {
          groupFramesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addGroupFrames(
          int index, com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame.Builder builderForValue) {
        if (groupFramesBuilder_ == null) {
          ensureGroupFramesIsMutable();
          groupFrames_.add(index, builderForValue.build());
          onChanged();
        } else {
          groupFramesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllGroupFrames(
          java.lang.Iterable<? extends com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame> values) {
        if (groupFramesBuilder_ == null) {
          ensureGroupFramesIsMutable();
          super.addAll(values, groupFrames_);
          onChanged();
        } else {
          groupFramesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearGroupFrames() {
        if (groupFramesBuilder_ == null) {
          groupFrames_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          groupFramesBuilder_.clear();
        }
        return this;
      }
      public Builder removeGroupFrames(int index) {
        if (groupFramesBuilder_ == null) {
          ensureGroupFramesIsMutable();
          groupFrames_.remove(index);
          onChanged();
        } else {
          groupFramesBuilder_.remove(index);
        }
        return this;
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame.Builder getGroupFramesBuilder(
          int index) {
        return getGroupFramesFieldBuilder().getBuilder(index);
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrameOrBuilder getGroupFramesOrBuilder(
          int index) {
        if (groupFramesBuilder_ == null) {
          return groupFrames_.get(index);  } else {
          return groupFramesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrameOrBuilder> 
           getGroupFramesOrBuilderList() {
        if (groupFramesBuilder_ != null) {
          return groupFramesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(groupFrames_);
        }
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame.Builder addGroupFramesBuilder() {
        return getGroupFramesFieldBuilder().addBuilder(
            com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame.getDefaultInstance());
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame.Builder addGroupFramesBuilder(
          int index) {
        return getGroupFramesFieldBuilder().addBuilder(
            index, com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame.getDefaultInstance());
      }
      public java.util.List<com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame.Builder> 
           getGroupFramesBuilderList() {
        return getGroupFramesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame, com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrameOrBuilder> 
          getGroupFramesFieldBuilder() {
        if (groupFramesBuilder_ == null) {
          groupFramesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame, com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrame.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.GroupFrameOrBuilder>(
                  groupFrames_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          groupFrames_ = null;
        }
        return groupFramesBuilder_;
      }
      
      // optional string attributes = 6;
      private java.lang.Object attributes_ = "";
      public boolean hasAttributes() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getAttributes() {
        java.lang.Object ref = attributes_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          attributes_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAttributes(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        attributes_ = value;
        onChanged();
        return this;
      }
      public Builder clearAttributes() {
        bitField0_ = (bitField0_ & ~0x00000020);
        attributes_ = getDefaultInstance().getAttributes();
        onChanged();
        return this;
      }
      void setAttributes(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        attributes_ = value;
        onChanged();
      }
      
      // optional int32 msgType = 8;
      private int msgType_ ;
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getMsgType() {
        return msgType_;
      }
      public Builder setMsgType(int value) {
        bitField0_ |= 0x00000040;
        msgType_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        msgType_ = 0;
        onChanged();
        return this;
      }
      
      // required .com.xuanwu.msggate.common.protobuf.pack.PRequestType requestType = 7;
      private com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequestType requestType_ = com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequestType.MESSAGE;
      public boolean hasRequestType() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequestType getRequestType() {
        return requestType_;
      }
      public Builder setRequestType(com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        requestType_ = value;
        onChanged();
        return this;
      }
      public Builder clearRequestType() {
        bitField0_ = (bitField0_ & ~0x00000080);
        requestType_ = com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequestType.MESSAGE;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.xuanwu.msggate.common.protobuf.pack.PRequest)
    }
    
    static {
      defaultInstance = new PRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.xuanwu.msggate.common.protobuf.pack.PRequest)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xuanwu_msggate_common_protobuf_pack_PRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_xuanwu_msggate_common_protobuf_pack_PRequest_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021PackRequest.proto\022\'com.xuanwu.msggate." +
      "common.protobuf.pack\032\020CommonItem.proto\"\352" +
      "\002\n\010PRequest\022:\n\010packUUID\030\001 \002(\0132(.com.xuan" +
      "wu.msggate.common.protobuf.UUID\022\027\n\017valid" +
      "FrameCount\030\002 \002(\005\022\020\n\010postTime\030\003 \002(\003\022A\n\nma" +
      "ssFrames\030\004 \003(\0132-.com.xuanwu.msggate.comm" +
      "on.protobuf.MassFrame\022C\n\013groupFrames\030\005 \003" +
      "(\0132..com.xuanwu.msggate.common.protobuf." +
      "GroupFrame\022\022\n\nattributes\030\006 \001(\t\022\017\n\007msgTyp" +
      "e\030\010 \001(\005\022J\n\013requestType\030\007 \002(\01625.com.xuanw",
      "u.msggate.common.protobuf.pack.PRequestT" +
      "ype*P\n\014PRequestType\022\013\n\007MESSAGE\020\000\022\022\n\016CHAN" +
      "NEL_CHANGE\020\001\022\023\n\017BUSINESS_CHANGE\020\002\022\n\n\006CAN" +
      "CEL\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_xuanwu_msggate_common_protobuf_pack_PRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_xuanwu_msggate_common_protobuf_pack_PRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_xuanwu_msggate_common_protobuf_pack_PRequest_descriptor,
              new java.lang.String[] { "PackUUID", "ValidFrameCount", "PostTime", "MassFrames", "GroupFrames", "Attributes", "MsgType", "RequestType", },
              com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest.class,
              com.xuanwu.msggate.common.protobuf.pack.PackRequest.PRequest.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.xuanwu.msggate.common.protobuf.CommonItem.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
