// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MTRequest.proto

package com.xuanwu.msggate.common.protobuf.mt;

public final class MTRequest {
  private MTRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum TRequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    LOGIN(0, 0),
    LOGOUT(1, 1),
    KEEPALIVE(2, 2),
    MESSAGE_SENT(3, 3),
    AUDITING(4, 4),
    CHANNEL_CHANGE(5, 5),
    BUSINESS_CHANGE(6, 6),
    ;
    
    public static final int LOGIN_VALUE = 0;
    public static final int LOGOUT_VALUE = 1;
    public static final int KEEPALIVE_VALUE = 2;
    public static final int MESSAGE_SENT_VALUE = 3;
    public static final int AUDITING_VALUE = 4;
    public static final int CHANNEL_CHANGE_VALUE = 5;
    public static final int BUSINESS_CHANGE_VALUE = 6;
    
    
    public final int getNumber() { return value; }
    
    public static TRequestType valueOf(int value) {
      switch (value) {
        case 0: return LOGIN;
        case 1: return LOGOUT;
        case 2: return KEEPALIVE;
        case 3: return MESSAGE_SENT;
        case 4: return AUDITING;
        case 5: return CHANNEL_CHANGE;
        case 6: return BUSINESS_CHANGE;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<TRequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TRequestType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TRequestType>() {
            public TRequestType findValueByNumber(int number) {
              return TRequestType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.xuanwu.msggate.common.protobuf.mt.MTRequest.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final TRequestType[] VALUES = {
      LOGIN, LOGOUT, KEEPALIVE, MESSAGE_SENT, AUDITING, CHANNEL_CHANGE, BUSINESS_CHANGE, 
    };
    
    public static TRequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private TRequestType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.xuanwu.msggate.common.protobuf.mt.TRequestType)
  }
  
  public interface TRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .com.xuanwu.msggate.common.protobuf.mt.TRequestType type = 1;
    boolean hasType();
    com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequestType getType();
    
    // optional .com.xuanwu.msggate.common.protobuf.UUID uuid = 2;
    boolean hasUuid();
    com.xuanwu.msggate.common.protobuf.CommonItem.UUID getUuid();
    com.xuanwu.msggate.common.protobuf.CommonItem.UUIDOrBuilder getUuidOrBuilder();
    
    // optional string batchName = 3;
    boolean hasBatchName();
    String getBatchName();
    
    // optional bool distinctFlag = 4;
    boolean hasDistinctFlag();
    boolean getDistinctFlag();
    
    // optional .com.xuanwu.msggate.common.protobuf.Account user = 5;
    boolean hasUser();
    com.xuanwu.msggate.common.protobuf.CommonItem.Account getUser();
    com.xuanwu.msggate.common.protobuf.CommonItem.AccountOrBuilder getUserOrBuilder();
    
    // optional string specNum = 6;
    boolean hasSpecNum();
    String getSpecNum();
    
    // optional string customNum = 7;
    boolean hasCustomNum();
    String getCustomNum();
    
    // optional bytes groupMsg = 8;
    boolean hasGroupMsg();
    com.google.protobuf.ByteString getGroupMsg();
    
    // optional bytes massMsg = 9;
    boolean hasMassMsg();
    com.google.protobuf.ByteString getMassMsg();
    
    // optional string attributes = 10;
    boolean hasAttributes();
    String getAttributes();
    
    // optional .com.xuanwu.msggate.common.protobuf.BizMeta info = 11;
    boolean hasInfo();
    com.xuanwu.msggate.common.protobuf.CommonItem.BizMeta getInfo();
    com.xuanwu.msggate.common.protobuf.CommonItem.BizMetaOrBuilder getInfoOrBuilder();
    
    // repeated .com.xuanwu.msggate.common.protobuf.MediaItem mmsAttachment = 12;
    java.util.List<com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem> 
        getMmsAttachmentList();
    com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem getMmsAttachment(int index);
    int getMmsAttachmentCount();
    java.util.List<? extends com.xuanwu.msggate.common.protobuf.CommonItem.MediaItemOrBuilder> 
        getMmsAttachmentOrBuilderList();
    com.xuanwu.msggate.common.protobuf.CommonItem.MediaItemOrBuilder getMmsAttachmentOrBuilder(
        int index);
    
    // optional int32 auditingState = 13;
    boolean hasAuditingState();
    int getAuditingState();
    
    // optional string from = 14;
    boolean hasFrom();
    String getFrom();
    
    // optional string remark = 15;
    boolean hasRemark();
    String getRemark();
  }
  public static final class TRequest extends
      com.google.protobuf.GeneratedMessage
      implements TRequestOrBuilder {
    // Use TRequest.newBuilder() to construct.
    private TRequest(Builder builder) {
      super(builder);
    }
    private TRequest(boolean noInit) {}
    
    private static final TRequest defaultInstance;
    public static TRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public TRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xuanwu.msggate.common.protobuf.mt.MTRequest.internal_static_com_xuanwu_msggate_common_protobuf_mt_TRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xuanwu.msggate.common.protobuf.mt.MTRequest.internal_static_com_xuanwu_msggate_common_protobuf_mt_TRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .com.xuanwu.msggate.common.protobuf.mt.TRequestType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequestType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequestType getType() {
      return type_;
    }
    
    // optional .com.xuanwu.msggate.common.protobuf.UUID uuid = 2;
    public static final int UUID_FIELD_NUMBER = 2;
    private com.xuanwu.msggate.common.protobuf.CommonItem.UUID uuid_;
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.xuanwu.msggate.common.protobuf.CommonItem.UUID getUuid() {
      return uuid_;
    }
    public com.xuanwu.msggate.common.protobuf.CommonItem.UUIDOrBuilder getUuidOrBuilder() {
      return uuid_;
    }
    
    // optional string batchName = 3;
    public static final int BATCHNAME_FIELD_NUMBER = 3;
    private java.lang.Object batchName_;
    public boolean hasBatchName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getBatchName() {
      java.lang.Object ref = batchName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          batchName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBatchNameBytes() {
      java.lang.Object ref = batchName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        batchName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool distinctFlag = 4;
    public static final int DISTINCTFLAG_FIELD_NUMBER = 4;
    private boolean distinctFlag_;
    public boolean hasDistinctFlag() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public boolean getDistinctFlag() {
      return distinctFlag_;
    }
    
    // optional .com.xuanwu.msggate.common.protobuf.Account user = 5;
    public static final int USER_FIELD_NUMBER = 5;
    private com.xuanwu.msggate.common.protobuf.CommonItem.Account user_;
    public boolean hasUser() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public com.xuanwu.msggate.common.protobuf.CommonItem.Account getUser() {
      return user_;
    }
    public com.xuanwu.msggate.common.protobuf.CommonItem.AccountOrBuilder getUserOrBuilder() {
      return user_;
    }
    
    // optional string specNum = 6;
    public static final int SPECNUM_FIELD_NUMBER = 6;
    private java.lang.Object specNum_;
    public boolean hasSpecNum() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getSpecNum() {
      java.lang.Object ref = specNum_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          specNum_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSpecNumBytes() {
      java.lang.Object ref = specNum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        specNum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string customNum = 7;
    public static final int CUSTOMNUM_FIELD_NUMBER = 7;
    private java.lang.Object customNum_;
    public boolean hasCustomNum() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getCustomNum() {
      java.lang.Object ref = customNum_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          customNum_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCustomNumBytes() {
      java.lang.Object ref = customNum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        customNum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes groupMsg = 8;
    public static final int GROUPMSG_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString groupMsg_;
    public boolean hasGroupMsg() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public com.google.protobuf.ByteString getGroupMsg() {
      return groupMsg_;
    }
    
    // optional bytes massMsg = 9;
    public static final int MASSMSG_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString massMsg_;
    public boolean hasMassMsg() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public com.google.protobuf.ByteString getMassMsg() {
      return massMsg_;
    }
    
    // optional string attributes = 10;
    public static final int ATTRIBUTES_FIELD_NUMBER = 10;
    private java.lang.Object attributes_;
    public boolean hasAttributes() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getAttributes() {
      java.lang.Object ref = attributes_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          attributes_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAttributesBytes() {
      java.lang.Object ref = attributes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        attributes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .com.xuanwu.msggate.common.protobuf.BizMeta info = 11;
    public static final int INFO_FIELD_NUMBER = 11;
    private com.xuanwu.msggate.common.protobuf.CommonItem.BizMeta info_;
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public com.xuanwu.msggate.common.protobuf.CommonItem.BizMeta getInfo() {
      return info_;
    }
    public com.xuanwu.msggate.common.protobuf.CommonItem.BizMetaOrBuilder getInfoOrBuilder() {
      return info_;
    }
    
    // repeated .com.xuanwu.msggate.common.protobuf.MediaItem mmsAttachment = 12;
    public static final int MMSATTACHMENT_FIELD_NUMBER = 12;
    private java.util.List<com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem> mmsAttachment_;
    public java.util.List<com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem> getMmsAttachmentList() {
      return mmsAttachment_;
    }
    public java.util.List<? extends com.xuanwu.msggate.common.protobuf.CommonItem.MediaItemOrBuilder> 
        getMmsAttachmentOrBuilderList() {
      return mmsAttachment_;
    }
    public int getMmsAttachmentCount() {
      return mmsAttachment_.size();
    }
    public com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem getMmsAttachment(int index) {
      return mmsAttachment_.get(index);
    }
    public com.xuanwu.msggate.common.protobuf.CommonItem.MediaItemOrBuilder getMmsAttachmentOrBuilder(
        int index) {
      return mmsAttachment_.get(index);
    }
    
    // optional int32 auditingState = 13;
    public static final int AUDITINGSTATE_FIELD_NUMBER = 13;
    private int auditingState_;
    public boolean hasAuditingState() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public int getAuditingState() {
      return auditingState_;
    }
    
    // optional string from = 14;
    public static final int FROM_FIELD_NUMBER = 14;
    private java.lang.Object from_;
    public boolean hasFrom() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public String getFrom() {
      java.lang.Object ref = from_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          from_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string remark = 15;
    public static final int REMARK_FIELD_NUMBER = 15;
    private java.lang.Object remark_;
    public boolean hasRemark() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    public String getRemark() {
      java.lang.Object ref = remark_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          remark_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRemarkBytes() {
      java.lang.Object ref = remark_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        remark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      type_ = com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequestType.LOGIN;
      uuid_ = com.xuanwu.msggate.common.protobuf.CommonItem.UUID.getDefaultInstance();
      batchName_ = "";
      distinctFlag_ = false;
      user_ = com.xuanwu.msggate.common.protobuf.CommonItem.Account.getDefaultInstance();
      specNum_ = "";
      customNum_ = "";
      groupMsg_ = com.google.protobuf.ByteString.EMPTY;
      massMsg_ = com.google.protobuf.ByteString.EMPTY;
      attributes_ = "";
      info_ = com.xuanwu.msggate.common.protobuf.CommonItem.BizMeta.getDefaultInstance();
      mmsAttachment_ = java.util.Collections.emptyList();
      auditingState_ = 0;
      from_ = "";
      remark_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasUuid()) {
        if (!getUuid().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasUser()) {
        if (!getUser().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasInfo()) {
        if (!getInfo().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getMmsAttachmentCount(); i++) {
        if (!getMmsAttachment(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, uuid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getBatchNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, distinctFlag_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, user_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getSpecNumBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getCustomNumBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, groupMsg_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, massMsg_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getAttributesBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeMessage(11, info_);
      }
      for (int i = 0; i < mmsAttachment_.size(); i++) {
        output.writeMessage(12, mmsAttachment_.get(i));
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(13, auditingState_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(14, getFromBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeBytes(15, getRemarkBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, uuid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getBatchNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, distinctFlag_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, user_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getSpecNumBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getCustomNumBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, groupMsg_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, massMsg_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getAttributesBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, info_);
      }
      for (int i = 0; i < mmsAttachment_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, mmsAttachment_.get(i));
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, auditingState_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, getFromBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, getRemarkBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xuanwu.msggate.common.protobuf.mt.MTRequest.internal_static_com_xuanwu_msggate_common_protobuf_mt_TRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xuanwu.msggate.common.protobuf.mt.MTRequest.internal_static_com_xuanwu_msggate_common_protobuf_mt_TRequest_fieldAccessorTable;
      }
      
      // Construct using com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUuidFieldBuilder();
          getUserFieldBuilder();
          getInfoFieldBuilder();
          getMmsAttachmentFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequestType.LOGIN;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (uuidBuilder_ == null) {
          uuid_ = com.xuanwu.msggate.common.protobuf.CommonItem.UUID.getDefaultInstance();
        } else {
          uuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        batchName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        distinctFlag_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (userBuilder_ == null) {
          user_ = com.xuanwu.msggate.common.protobuf.CommonItem.Account.getDefaultInstance();
        } else {
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        specNum_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        customNum_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        groupMsg_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        massMsg_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        attributes_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        if (infoBuilder_ == null) {
          info_ = com.xuanwu.msggate.common.protobuf.CommonItem.BizMeta.getDefaultInstance();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000400);
        if (mmsAttachmentBuilder_ == null) {
          mmsAttachment_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000800);
        } else {
          mmsAttachmentBuilder_.clear();
        }
        auditingState_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        from_ = "";
        bitField0_ = (bitField0_ & ~0x00002000);
        remark_ = "";
        bitField0_ = (bitField0_ & ~0x00004000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest.getDescriptor();
      }
      
      public com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest getDefaultInstanceForType() {
        return com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest.getDefaultInstance();
      }
      
      public com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest build() {
        com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest buildPartial() {
        com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest result = new com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (uuidBuilder_ == null) {
          result.uuid_ = uuid_;
        } else {
          result.uuid_ = uuidBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.batchName_ = batchName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.distinctFlag_ = distinctFlag_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.specNum_ = specNum_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.customNum_ = customNum_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.groupMsg_ = groupMsg_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.massMsg_ = massMsg_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.attributes_ = attributes_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        if (infoBuilder_ == null) {
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        if (mmsAttachmentBuilder_ == null) {
          if (((bitField0_ & 0x00000800) == 0x00000800)) {
            mmsAttachment_ = java.util.Collections.unmodifiableList(mmsAttachment_);
            bitField0_ = (bitField0_ & ~0x00000800);
          }
          result.mmsAttachment_ = mmsAttachment_;
        } else {
          result.mmsAttachment_ = mmsAttachmentBuilder_.build();
        }
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00000800;
        }
        result.auditingState_ = auditingState_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.from_ = from_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.remark_ = remark_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest) {
          return mergeFrom((com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest other) {
        if (other == com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasUuid()) {
          mergeUuid(other.getUuid());
        }
        if (other.hasBatchName()) {
          setBatchName(other.getBatchName());
        }
        if (other.hasDistinctFlag()) {
          setDistinctFlag(other.getDistinctFlag());
        }
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        if (other.hasSpecNum()) {
          setSpecNum(other.getSpecNum());
        }
        if (other.hasCustomNum()) {
          setCustomNum(other.getCustomNum());
        }
        if (other.hasGroupMsg()) {
          setGroupMsg(other.getGroupMsg());
        }
        if (other.hasMassMsg()) {
          setMassMsg(other.getMassMsg());
        }
        if (other.hasAttributes()) {
          setAttributes(other.getAttributes());
        }
        if (other.hasInfo()) {
          mergeInfo(other.getInfo());
        }
        if (mmsAttachmentBuilder_ == null) {
          if (!other.mmsAttachment_.isEmpty()) {
            if (mmsAttachment_.isEmpty()) {
              mmsAttachment_ = other.mmsAttachment_;
              bitField0_ = (bitField0_ & ~0x00000800);
            } else {
              ensureMmsAttachmentIsMutable();
              mmsAttachment_.addAll(other.mmsAttachment_);
            }
            onChanged();
          }
        } else {
          if (!other.mmsAttachment_.isEmpty()) {
            if (mmsAttachmentBuilder_.isEmpty()) {
              mmsAttachmentBuilder_.dispose();
              mmsAttachmentBuilder_ = null;
              mmsAttachment_ = other.mmsAttachment_;
              bitField0_ = (bitField0_ & ~0x00000800);
              mmsAttachmentBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMmsAttachmentFieldBuilder() : null;
            } else {
              mmsAttachmentBuilder_.addAllMessages(other.mmsAttachment_);
            }
          }
        }
        if (other.hasAuditingState()) {
          setAuditingState(other.getAuditingState());
        }
        if (other.hasFrom()) {
          setFrom(other.getFrom());
        }
        if (other.hasRemark()) {
          setRemark(other.getRemark());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasUuid()) {
          if (!getUuid().isInitialized()) {
            
            return false;
          }
        }
        if (hasUser()) {
          if (!getUser().isInitialized()) {
            
            return false;
          }
        }
        if (hasInfo()) {
          if (!getInfo().isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getMmsAttachmentCount(); i++) {
          if (!getMmsAttachment(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequestType value = com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequestType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              com.xuanwu.msggate.common.protobuf.CommonItem.UUID.Builder subBuilder = com.xuanwu.msggate.common.protobuf.CommonItem.UUID.newBuilder();
              if (hasUuid()) {
                subBuilder.mergeFrom(getUuid());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setUuid(subBuilder.buildPartial());
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              batchName_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              distinctFlag_ = input.readBool();
              break;
            }
            case 42: {
              com.xuanwu.msggate.common.protobuf.CommonItem.Account.Builder subBuilder = com.xuanwu.msggate.common.protobuf.CommonItem.Account.newBuilder();
              if (hasUser()) {
                subBuilder.mergeFrom(getUser());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setUser(subBuilder.buildPartial());
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              specNum_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              customNum_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              groupMsg_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              massMsg_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              attributes_ = input.readBytes();
              break;
            }
            case 90: {
              com.xuanwu.msggate.common.protobuf.CommonItem.BizMeta.Builder subBuilder = com.xuanwu.msggate.common.protobuf.CommonItem.BizMeta.newBuilder();
              if (hasInfo()) {
                subBuilder.mergeFrom(getInfo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setInfo(subBuilder.buildPartial());
              break;
            }
            case 98: {
              com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem.Builder subBuilder = com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMmsAttachment(subBuilder.buildPartial());
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              auditingState_ = input.readInt32();
              break;
            }
            case 114: {
              bitField0_ |= 0x00002000;
              from_ = input.readBytes();
              break;
            }
            case 122: {
              bitField0_ |= 0x00004000;
              remark_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .com.xuanwu.msggate.common.protobuf.mt.TRequestType type = 1;
      private com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequestType type_ = com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequestType.LOGIN;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequestType getType() {
        return type_;
      }
      public Builder setType(com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequestType.LOGIN;
        onChanged();
        return this;
      }
      
      // optional .com.xuanwu.msggate.common.protobuf.UUID uuid = 2;
      private com.xuanwu.msggate.common.protobuf.CommonItem.UUID uuid_ = com.xuanwu.msggate.common.protobuf.CommonItem.UUID.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.xuanwu.msggate.common.protobuf.CommonItem.UUID, com.xuanwu.msggate.common.protobuf.CommonItem.UUID.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.UUIDOrBuilder> uuidBuilder_;
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.UUID getUuid() {
        if (uuidBuilder_ == null) {
          return uuid_;
        } else {
          return uuidBuilder_.getMessage();
        }
      }
      public Builder setUuid(com.xuanwu.msggate.common.protobuf.CommonItem.UUID value) {
        if (uuidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          uuid_ = value;
          onChanged();
        } else {
          uuidBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setUuid(
          com.xuanwu.msggate.common.protobuf.CommonItem.UUID.Builder builderForValue) {
        if (uuidBuilder_ == null) {
          uuid_ = builderForValue.build();
          onChanged();
        } else {
          uuidBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeUuid(com.xuanwu.msggate.common.protobuf.CommonItem.UUID value) {
        if (uuidBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              uuid_ != com.xuanwu.msggate.common.protobuf.CommonItem.UUID.getDefaultInstance()) {
            uuid_ =
              com.xuanwu.msggate.common.protobuf.CommonItem.UUID.newBuilder(uuid_).mergeFrom(value).buildPartial();
          } else {
            uuid_ = value;
          }
          onChanged();
        } else {
          uuidBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearUuid() {
        if (uuidBuilder_ == null) {
          uuid_ = com.xuanwu.msggate.common.protobuf.CommonItem.UUID.getDefaultInstance();
          onChanged();
        } else {
          uuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.UUID.Builder getUuidBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getUuidFieldBuilder().getBuilder();
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.UUIDOrBuilder getUuidOrBuilder() {
        if (uuidBuilder_ != null) {
          return uuidBuilder_.getMessageOrBuilder();
        } else {
          return uuid_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.xuanwu.msggate.common.protobuf.CommonItem.UUID, com.xuanwu.msggate.common.protobuf.CommonItem.UUID.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.UUIDOrBuilder> 
          getUuidFieldBuilder() {
        if (uuidBuilder_ == null) {
          uuidBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.xuanwu.msggate.common.protobuf.CommonItem.UUID, com.xuanwu.msggate.common.protobuf.CommonItem.UUID.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.UUIDOrBuilder>(
                  uuid_,
                  getParentForChildren(),
                  isClean());
          uuid_ = null;
        }
        return uuidBuilder_;
      }
      
      // optional string batchName = 3;
      private java.lang.Object batchName_ = "";
      public boolean hasBatchName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getBatchName() {
        java.lang.Object ref = batchName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          batchName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBatchName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        batchName_ = value;
        onChanged();
        return this;
      }
      public Builder clearBatchName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        batchName_ = getDefaultInstance().getBatchName();
        onChanged();
        return this;
      }
      void setBatchName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        batchName_ = value;
        onChanged();
      }
      
      // optional bool distinctFlag = 4;
      private boolean distinctFlag_ ;
      public boolean hasDistinctFlag() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public boolean getDistinctFlag() {
        return distinctFlag_;
      }
      public Builder setDistinctFlag(boolean value) {
        bitField0_ |= 0x00000008;
        distinctFlag_ = value;
        onChanged();
        return this;
      }
      public Builder clearDistinctFlag() {
        bitField0_ = (bitField0_ & ~0x00000008);
        distinctFlag_ = false;
        onChanged();
        return this;
      }
      
      // optional .com.xuanwu.msggate.common.protobuf.Account user = 5;
      private com.xuanwu.msggate.common.protobuf.CommonItem.Account user_ = com.xuanwu.msggate.common.protobuf.CommonItem.Account.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.xuanwu.msggate.common.protobuf.CommonItem.Account, com.xuanwu.msggate.common.protobuf.CommonItem.Account.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.AccountOrBuilder> userBuilder_;
      public boolean hasUser() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.Account getUser() {
        if (userBuilder_ == null) {
          return user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      public Builder setUser(com.xuanwu.msggate.common.protobuf.CommonItem.Account value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder setUser(
          com.xuanwu.msggate.common.protobuf.CommonItem.Account.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder mergeUser(com.xuanwu.msggate.common.protobuf.CommonItem.Account value) {
        if (userBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              user_ != com.xuanwu.msggate.common.protobuf.CommonItem.Account.getDefaultInstance()) {
            user_ =
              com.xuanwu.msggate.common.protobuf.CommonItem.Account.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = com.xuanwu.msggate.common.protobuf.CommonItem.Account.getDefaultInstance();
          onChanged();
        } else {
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.Account.Builder getUserBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.AccountOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.xuanwu.msggate.common.protobuf.CommonItem.Account, com.xuanwu.msggate.common.protobuf.CommonItem.Account.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.AccountOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.xuanwu.msggate.common.protobuf.CommonItem.Account, com.xuanwu.msggate.common.protobuf.CommonItem.Account.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.AccountOrBuilder>(
                  user_,
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }
      
      // optional string specNum = 6;
      private java.lang.Object specNum_ = "";
      public boolean hasSpecNum() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getSpecNum() {
        java.lang.Object ref = specNum_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          specNum_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSpecNum(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        specNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearSpecNum() {
        bitField0_ = (bitField0_ & ~0x00000020);
        specNum_ = getDefaultInstance().getSpecNum();
        onChanged();
        return this;
      }
      void setSpecNum(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        specNum_ = value;
        onChanged();
      }
      
      // optional string customNum = 7;
      private java.lang.Object customNum_ = "";
      public boolean hasCustomNum() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getCustomNum() {
        java.lang.Object ref = customNum_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          customNum_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCustomNum(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        customNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearCustomNum() {
        bitField0_ = (bitField0_ & ~0x00000040);
        customNum_ = getDefaultInstance().getCustomNum();
        onChanged();
        return this;
      }
      void setCustomNum(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        customNum_ = value;
        onChanged();
      }
      
      // optional bytes groupMsg = 8;
      private com.google.protobuf.ByteString groupMsg_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasGroupMsg() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public com.google.protobuf.ByteString getGroupMsg() {
        return groupMsg_;
      }
      public Builder setGroupMsg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        groupMsg_ = value;
        onChanged();
        return this;
      }
      public Builder clearGroupMsg() {
        bitField0_ = (bitField0_ & ~0x00000080);
        groupMsg_ = getDefaultInstance().getGroupMsg();
        onChanged();
        return this;
      }
      
      // optional bytes massMsg = 9;
      private com.google.protobuf.ByteString massMsg_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasMassMsg() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public com.google.protobuf.ByteString getMassMsg() {
        return massMsg_;
      }
      public Builder setMassMsg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        massMsg_ = value;
        onChanged();
        return this;
      }
      public Builder clearMassMsg() {
        bitField0_ = (bitField0_ & ~0x00000100);
        massMsg_ = getDefaultInstance().getMassMsg();
        onChanged();
        return this;
      }
      
      // optional string attributes = 10;
      private java.lang.Object attributes_ = "";
      public boolean hasAttributes() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getAttributes() {
        java.lang.Object ref = attributes_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          attributes_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAttributes(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        attributes_ = value;
        onChanged();
        return this;
      }
      public Builder clearAttributes() {
        bitField0_ = (bitField0_ & ~0x00000200);
        attributes_ = getDefaultInstance().getAttributes();
        onChanged();
        return this;
      }
      void setAttributes(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        attributes_ = value;
        onChanged();
      }
      
      // optional .com.xuanwu.msggate.common.protobuf.BizMeta info = 11;
      private com.xuanwu.msggate.common.protobuf.CommonItem.BizMeta info_ = com.xuanwu.msggate.common.protobuf.CommonItem.BizMeta.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.xuanwu.msggate.common.protobuf.CommonItem.BizMeta, com.xuanwu.msggate.common.protobuf.CommonItem.BizMeta.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.BizMetaOrBuilder> infoBuilder_;
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.BizMeta getInfo() {
        if (infoBuilder_ == null) {
          return info_;
        } else {
          return infoBuilder_.getMessage();
        }
      }
      public Builder setInfo(com.xuanwu.msggate.common.protobuf.CommonItem.BizMeta value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          info_ = value;
          onChanged();
        } else {
          infoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000400;
        return this;
      }
      public Builder setInfo(
          com.xuanwu.msggate.common.protobuf.CommonItem.BizMeta.Builder builderForValue) {
        if (infoBuilder_ == null) {
          info_ = builderForValue.build();
          onChanged();
        } else {
          infoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000400;
        return this;
      }
      public Builder mergeInfo(com.xuanwu.msggate.common.protobuf.CommonItem.BizMeta value) {
        if (infoBuilder_ == null) {
          if (((bitField0_ & 0x00000400) == 0x00000400) &&
              info_ != com.xuanwu.msggate.common.protobuf.CommonItem.BizMeta.getDefaultInstance()) {
            info_ =
              com.xuanwu.msggate.common.protobuf.CommonItem.BizMeta.newBuilder(info_).mergeFrom(value).buildPartial();
          } else {
            info_ = value;
          }
          onChanged();
        } else {
          infoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000400;
        return this;
      }
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = com.xuanwu.msggate.common.protobuf.CommonItem.BizMeta.getDefaultInstance();
          onChanged();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.BizMeta.Builder getInfoBuilder() {
        bitField0_ |= 0x00000400;
        onChanged();
        return getInfoFieldBuilder().getBuilder();
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.BizMetaOrBuilder getInfoOrBuilder() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilder();
        } else {
          return info_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.xuanwu.msggate.common.protobuf.CommonItem.BizMeta, com.xuanwu.msggate.common.protobuf.CommonItem.BizMeta.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.BizMetaOrBuilder> 
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.xuanwu.msggate.common.protobuf.CommonItem.BizMeta, com.xuanwu.msggate.common.protobuf.CommonItem.BizMeta.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.BizMetaOrBuilder>(
                  info_,
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }
      
      // repeated .com.xuanwu.msggate.common.protobuf.MediaItem mmsAttachment = 12;
      private java.util.List<com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem> mmsAttachment_ =
        java.util.Collections.emptyList();
      private void ensureMmsAttachmentIsMutable() {
        if (!((bitField0_ & 0x00000800) == 0x00000800)) {
          mmsAttachment_ = new java.util.ArrayList<com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem>(mmsAttachment_);
          bitField0_ |= 0x00000800;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem, com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.MediaItemOrBuilder> mmsAttachmentBuilder_;
      
      public java.util.List<com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem> getMmsAttachmentList() {
        if (mmsAttachmentBuilder_ == null) {
          return java.util.Collections.unmodifiableList(mmsAttachment_);
        } else {
          return mmsAttachmentBuilder_.getMessageList();
        }
      }
      public int getMmsAttachmentCount() {
        if (mmsAttachmentBuilder_ == null) {
          return mmsAttachment_.size();
        } else {
          return mmsAttachmentBuilder_.getCount();
        }
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem getMmsAttachment(int index) {
        if (mmsAttachmentBuilder_ == null) {
          return mmsAttachment_.get(index);
        } else {
          return mmsAttachmentBuilder_.getMessage(index);
        }
      }
      public Builder setMmsAttachment(
          int index, com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem value) {
        if (mmsAttachmentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMmsAttachmentIsMutable();
          mmsAttachment_.set(index, value);
          onChanged();
        } else {
          mmsAttachmentBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setMmsAttachment(
          int index, com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem.Builder builderForValue) {
        if (mmsAttachmentBuilder_ == null) {
          ensureMmsAttachmentIsMutable();
          mmsAttachment_.set(index, builderForValue.build());
          onChanged();
        } else {
          mmsAttachmentBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addMmsAttachment(com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem value) {
        if (mmsAttachmentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMmsAttachmentIsMutable();
          mmsAttachment_.add(value);
          onChanged();
        } else {
          mmsAttachmentBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addMmsAttachment(
          int index, com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem value) {
        if (mmsAttachmentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMmsAttachmentIsMutable();
          mmsAttachment_.add(index, value);
          onChanged();
        } else {
          mmsAttachmentBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addMmsAttachment(
          com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem.Builder builderForValue) {
        if (mmsAttachmentBuilder_ == null) {
          ensureMmsAttachmentIsMutable();
          mmsAttachment_.add(builderForValue.build());
          onChanged();
        } else {
          mmsAttachmentBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addMmsAttachment(
          int index, com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem.Builder builderForValue) {
        if (mmsAttachmentBuilder_ == null) {
          ensureMmsAttachmentIsMutable();
          mmsAttachment_.add(index, builderForValue.build());
          onChanged();
        } else {
          mmsAttachmentBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllMmsAttachment(
          java.lang.Iterable<? extends com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem> values) {
        if (mmsAttachmentBuilder_ == null) {
          ensureMmsAttachmentIsMutable();
          super.addAll(values, mmsAttachment_);
          onChanged();
        } else {
          mmsAttachmentBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearMmsAttachment() {
        if (mmsAttachmentBuilder_ == null) {
          mmsAttachment_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000800);
          onChanged();
        } else {
          mmsAttachmentBuilder_.clear();
        }
        return this;
      }
      public Builder removeMmsAttachment(int index) {
        if (mmsAttachmentBuilder_ == null) {
          ensureMmsAttachmentIsMutable();
          mmsAttachment_.remove(index);
          onChanged();
        } else {
          mmsAttachmentBuilder_.remove(index);
        }
        return this;
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem.Builder getMmsAttachmentBuilder(
          int index) {
        return getMmsAttachmentFieldBuilder().getBuilder(index);
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.MediaItemOrBuilder getMmsAttachmentOrBuilder(
          int index) {
        if (mmsAttachmentBuilder_ == null) {
          return mmsAttachment_.get(index);  } else {
          return mmsAttachmentBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.xuanwu.msggate.common.protobuf.CommonItem.MediaItemOrBuilder> 
           getMmsAttachmentOrBuilderList() {
        if (mmsAttachmentBuilder_ != null) {
          return mmsAttachmentBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(mmsAttachment_);
        }
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem.Builder addMmsAttachmentBuilder() {
        return getMmsAttachmentFieldBuilder().addBuilder(
            com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem.getDefaultInstance());
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem.Builder addMmsAttachmentBuilder(
          int index) {
        return getMmsAttachmentFieldBuilder().addBuilder(
            index, com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem.getDefaultInstance());
      }
      public java.util.List<com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem.Builder> 
           getMmsAttachmentBuilderList() {
        return getMmsAttachmentFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem, com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.MediaItemOrBuilder> 
          getMmsAttachmentFieldBuilder() {
        if (mmsAttachmentBuilder_ == null) {
          mmsAttachmentBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem, com.xuanwu.msggate.common.protobuf.CommonItem.MediaItem.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.MediaItemOrBuilder>(
                  mmsAttachment_,
                  ((bitField0_ & 0x00000800) == 0x00000800),
                  getParentForChildren(),
                  isClean());
          mmsAttachment_ = null;
        }
        return mmsAttachmentBuilder_;
      }
      
      // optional int32 auditingState = 13;
      private int auditingState_ ;
      public boolean hasAuditingState() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public int getAuditingState() {
        return auditingState_;
      }
      public Builder setAuditingState(int value) {
        bitField0_ |= 0x00001000;
        auditingState_ = value;
        onChanged();
        return this;
      }
      public Builder clearAuditingState() {
        bitField0_ = (bitField0_ & ~0x00001000);
        auditingState_ = 0;
        onChanged();
        return this;
      }
      
      // optional string from = 14;
      private java.lang.Object from_ = "";
      public boolean hasFrom() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      public String getFrom() {
        java.lang.Object ref = from_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          from_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFrom(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        from_ = value;
        onChanged();
        return this;
      }
      public Builder clearFrom() {
        bitField0_ = (bitField0_ & ~0x00002000);
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }
      void setFrom(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00002000;
        from_ = value;
        onChanged();
      }
      
      // optional string remark = 15;
      private java.lang.Object remark_ = "";
      public boolean hasRemark() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      public String getRemark() {
        java.lang.Object ref = remark_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          remark_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRemark(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        remark_ = value;
        onChanged();
        return this;
      }
      public Builder clearRemark() {
        bitField0_ = (bitField0_ & ~0x00004000);
        remark_ = getDefaultInstance().getRemark();
        onChanged();
        return this;
      }
      void setRemark(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00004000;
        remark_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.xuanwu.msggate.common.protobuf.mt.TRequest)
    }
    
    static {
      defaultInstance = new TRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.xuanwu.msggate.common.protobuf.mt.TRequest)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xuanwu_msggate_common_protobuf_mt_TRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_xuanwu_msggate_common_protobuf_mt_TRequest_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017MTRequest.proto\022%com.xuanwu.msggate.co" +
      "mmon.protobuf.mt\032\020CommonItem.proto\"\372\003\n\010T" +
      "Request\022A\n\004type\030\001 \002(\01623.com.xuanwu.msgga" +
      "te.common.protobuf.mt.TRequestType\0226\n\004uu" +
      "id\030\002 \001(\0132(.com.xuanwu.msggate.common.pro" +
      "tobuf.UUID\022\021\n\tbatchName\030\003 \001(\t\022\024\n\014distinc" +
      "tFlag\030\004 \001(\010\0229\n\004user\030\005 \001(\0132+.com.xuanwu.m" +
      "sggate.common.protobuf.Account\022\017\n\007specNu" +
      "m\030\006 \001(\t\022\021\n\tcustomNum\030\007 \001(\t\022\020\n\010groupMsg\030\010" +
      " \001(\014\022\017\n\007massMsg\030\t \001(\014\022\022\n\nattributes\030\n \001(",
      "\t\0229\n\004info\030\013 \001(\0132+.com.xuanwu.msggate.com" +
      "mon.protobuf.BizMeta\022D\n\rmmsAttachment\030\014 " +
      "\003(\0132-.com.xuanwu.msggate.common.protobuf" +
      ".MediaItem\022\025\n\rauditingState\030\r \001(\005\022\014\n\004fro" +
      "m\030\016 \001(\t\022\016\n\006remark\030\017 \001(\t*}\n\014TRequestType\022" +
      "\t\n\005LOGIN\020\000\022\n\n\006LOGOUT\020\001\022\r\n\tKEEPALIVE\020\002\022\020\n" +
      "\014MESSAGE_SENT\020\003\022\014\n\010AUDITING\020\004\022\022\n\016CHANNEL" +
      "_CHANGE\020\005\022\023\n\017BUSINESS_CHANGE\020\006"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_xuanwu_msggate_common_protobuf_mt_TRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_xuanwu_msggate_common_protobuf_mt_TRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_xuanwu_msggate_common_protobuf_mt_TRequest_descriptor,
              new java.lang.String[] { "Type", "Uuid", "BatchName", "DistinctFlag", "User", "SpecNum", "CustomNum", "GroupMsg", "MassMsg", "Attributes", "Info", "MmsAttachment", "AuditingState", "From", "Remark", },
              com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest.class,
              com.xuanwu.msggate.common.protobuf.mt.MTRequest.TRequest.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.xuanwu.msggate.common.protobuf.CommonItem.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
