server:
    port: 9000
    contextPath: /mos/service
    session:
        timeout: 1800

spring:
    application:
        name: mos

datasource:
    gsms:
        name: gsmsDS
        driverClassName: com.mysql.jdbc.Driver

        url: jdbc:mysql://172.16.0.49:3306/mos5.0_gsms0703?useSSL=false&autoReconnect=true&sessionVariables=FOREIGN_KEY_CHECKS=0&useUnicode=yes&characterEncoding=UTF-8
        username: root
        password: 123456
        maxTotal: 200
        maxIdle: 8
        minIdle: 8
        initialSize: 10
        maxWaitMillis: 3000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        
    list:
        name: listDS
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://172.16.0.49:3306/mos5.0_list0703?useSSL=false&autoReconnect=true&sessionVariables=FOREIGN_KEY_CHECKS=0&useUnicode=yes&characterEncoding=UTF-8
        username: root
        password: 123456
        maxTotal: 200
        maxIdle: 8
        minIdle: 8
        initialSize: 10
        maxWaitMillis: 3000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false

mybatis:
    config-location: classpath:mybatis-config.xml

shiro:
    loginUrl: /login
    unauthorizedUrl : /login/unauthorized
    filters:
        /login/**: anonymous
        /**: authorization

fileUploadConfig:
    inputName: file
    rootFolder: /temp/upload/
    exts:
        image: jpg,jpeg,png,gif,bmp
        document: pdf,doc,docx,txt,csv,xls,xlsx
        audio: mp3,wma,wav,amr
        rar: rar,zip
    maxSize:
        image: 2
        document: 2
        audio: 5
        rar: 10


fileTask:
        maxPoolSize: 50000
        fetchUnloadTaskPeriod: 3000000