// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PackResponse.proto

package com.xuanwu.msggate.common.protobuf.pack;

public final class PackResponse {
  private PackResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum PResult
      implements com.google.protobuf.ProtocolMessageEnum {
    SUCCESS_FLAG(0, 0),
    INNER_ERROR_FLAG(1, 1),
    DUPLICATE_FLAG(2, 2),
    ;
    
    public static final int SUCCESS_FLAG_VALUE = 0;
    public static final int INNER_ERROR_FLAG_VALUE = 1;
    public static final int DUPLICATE_FLAG_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static PResult valueOf(int value) {
      switch (value) {
        case 0: return SUCCESS_FLAG;
        case 1: return INNER_ERROR_FLAG;
        case 2: return DUPLICATE_FLAG;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<PResult>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PResult>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PResult>() {
            public PResult findValueByNumber(int number) {
              return PResult.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.xuanwu.msggate.common.protobuf.pack.PackResponse.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final PResult[] VALUES = {
      SUCCESS_FLAG, INNER_ERROR_FLAG, DUPLICATE_FLAG, 
    };
    
    public static PResult valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private PResult(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.xuanwu.msggate.common.protobuf.pack.PResult)
  }
  
  public interface PResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .com.xuanwu.msggate.common.protobuf.pack.PResult result = 1;
    boolean hasResult();
    com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResult getResult();
    
    // optional .com.xuanwu.msggate.common.protobuf.UUID packUUID = 2;
    boolean hasPackUUID();
    com.xuanwu.msggate.common.protobuf.CommonItem.UUID getPackUUID();
    com.xuanwu.msggate.common.protobuf.CommonItem.UUIDOrBuilder getPackUUIDOrBuilder();
    
    // optional string message = 3;
    boolean hasMessage();
    String getMessage();
    
    // optional string attributes = 4;
    boolean hasAttributes();
    String getAttributes();
  }
  public static final class PResponse extends
      com.google.protobuf.GeneratedMessage
      implements PResponseOrBuilder {
    // Use PResponse.newBuilder() to construct.
    private PResponse(Builder builder) {
      super(builder);
    }
    private PResponse(boolean noInit) {}
    
    private static final PResponse defaultInstance;
    public static PResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public PResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xuanwu.msggate.common.protobuf.pack.PackResponse.internal_static_com_xuanwu_msggate_common_protobuf_pack_PResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xuanwu.msggate.common.protobuf.pack.PackResponse.internal_static_com_xuanwu_msggate_common_protobuf_pack_PResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .com.xuanwu.msggate.common.protobuf.pack.PResult result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResult result_;
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResult getResult() {
      return result_;
    }
    
    // optional .com.xuanwu.msggate.common.protobuf.UUID packUUID = 2;
    public static final int PACKUUID_FIELD_NUMBER = 2;
    private com.xuanwu.msggate.common.protobuf.CommonItem.UUID packUUID_;
    public boolean hasPackUUID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.xuanwu.msggate.common.protobuf.CommonItem.UUID getPackUUID() {
      return packUUID_;
    }
    public com.xuanwu.msggate.common.protobuf.CommonItem.UUIDOrBuilder getPackUUIDOrBuilder() {
      return packUUID_;
    }
    
    // optional string message = 3;
    public static final int MESSAGE_FIELD_NUMBER = 3;
    private java.lang.Object message_;
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          message_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string attributes = 4;
    public static final int ATTRIBUTES_FIELD_NUMBER = 4;
    private java.lang.Object attributes_;
    public boolean hasAttributes() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getAttributes() {
      java.lang.Object ref = attributes_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          attributes_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAttributesBytes() {
      java.lang.Object ref = attributes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        attributes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      result_ = com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResult.SUCCESS_FLAG;
      packUUID_ = com.xuanwu.msggate.common.protobuf.CommonItem.UUID.getDefaultInstance();
      message_ = "";
      attributes_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasPackUUID()) {
        if (!getPackUUID().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, result_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, packUUID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMessageBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getAttributesBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, result_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, packUUID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMessageBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getAttributesBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xuanwu.msggate.common.protobuf.pack.PackResponse.internal_static_com_xuanwu_msggate_common_protobuf_pack_PResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xuanwu.msggate.common.protobuf.pack.PackResponse.internal_static_com_xuanwu_msggate_common_protobuf_pack_PResponse_fieldAccessorTable;
      }
      
      // Construct using com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPackUUIDFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        result_ = com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResult.SUCCESS_FLAG;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (packUUIDBuilder_ == null) {
          packUUID_ = com.xuanwu.msggate.common.protobuf.CommonItem.UUID.getDefaultInstance();
        } else {
          packUUIDBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        attributes_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse.getDescriptor();
      }
      
      public com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse getDefaultInstanceForType() {
        return com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse.getDefaultInstance();
      }
      
      public com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse build() {
        com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse buildPartial() {
        com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse result = new com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (packUUIDBuilder_ == null) {
          result.packUUID_ = packUUID_;
        } else {
          result.packUUID_ = packUUIDBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.message_ = message_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.attributes_ = attributes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse) {
          return mergeFrom((com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse other) {
        if (other == com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasPackUUID()) {
          mergePackUUID(other.getPackUUID());
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        if (other.hasAttributes()) {
          setAttributes(other.getAttributes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        if (hasPackUUID()) {
          if (!getPackUUID().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResult value = com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResult.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                result_ = value;
              }
              break;
            }
            case 18: {
              com.xuanwu.msggate.common.protobuf.CommonItem.UUID.Builder subBuilder = com.xuanwu.msggate.common.protobuf.CommonItem.UUID.newBuilder();
              if (hasPackUUID()) {
                subBuilder.mergeFrom(getPackUUID());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPackUUID(subBuilder.buildPartial());
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              message_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              attributes_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .com.xuanwu.msggate.common.protobuf.pack.PResult result = 1;
      private com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResult result_ = com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResult.SUCCESS_FLAG;
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResult getResult() {
        return result_;
      }
      public Builder setResult(com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResult value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResult.SUCCESS_FLAG;
        onChanged();
        return this;
      }
      
      // optional .com.xuanwu.msggate.common.protobuf.UUID packUUID = 2;
      private com.xuanwu.msggate.common.protobuf.CommonItem.UUID packUUID_ = com.xuanwu.msggate.common.protobuf.CommonItem.UUID.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.xuanwu.msggate.common.protobuf.CommonItem.UUID, com.xuanwu.msggate.common.protobuf.CommonItem.UUID.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.UUIDOrBuilder> packUUIDBuilder_;
      public boolean hasPackUUID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.UUID getPackUUID() {
        if (packUUIDBuilder_ == null) {
          return packUUID_;
        } else {
          return packUUIDBuilder_.getMessage();
        }
      }
      public Builder setPackUUID(com.xuanwu.msggate.common.protobuf.CommonItem.UUID value) {
        if (packUUIDBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          packUUID_ = value;
          onChanged();
        } else {
          packUUIDBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setPackUUID(
          com.xuanwu.msggate.common.protobuf.CommonItem.UUID.Builder builderForValue) {
        if (packUUIDBuilder_ == null) {
          packUUID_ = builderForValue.build();
          onChanged();
        } else {
          packUUIDBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergePackUUID(com.xuanwu.msggate.common.protobuf.CommonItem.UUID value) {
        if (packUUIDBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              packUUID_ != com.xuanwu.msggate.common.protobuf.CommonItem.UUID.getDefaultInstance()) {
            packUUID_ =
              com.xuanwu.msggate.common.protobuf.CommonItem.UUID.newBuilder(packUUID_).mergeFrom(value).buildPartial();
          } else {
            packUUID_ = value;
          }
          onChanged();
        } else {
          packUUIDBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearPackUUID() {
        if (packUUIDBuilder_ == null) {
          packUUID_ = com.xuanwu.msggate.common.protobuf.CommonItem.UUID.getDefaultInstance();
          onChanged();
        } else {
          packUUIDBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.UUID.Builder getPackUUIDBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPackUUIDFieldBuilder().getBuilder();
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.UUIDOrBuilder getPackUUIDOrBuilder() {
        if (packUUIDBuilder_ != null) {
          return packUUIDBuilder_.getMessageOrBuilder();
        } else {
          return packUUID_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.xuanwu.msggate.common.protobuf.CommonItem.UUID, com.xuanwu.msggate.common.protobuf.CommonItem.UUID.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.UUIDOrBuilder> 
          getPackUUIDFieldBuilder() {
        if (packUUIDBuilder_ == null) {
          packUUIDBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.xuanwu.msggate.common.protobuf.CommonItem.UUID, com.xuanwu.msggate.common.protobuf.CommonItem.UUID.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.UUIDOrBuilder>(
                  packUUID_,
                  getParentForChildren(),
                  isClean());
          packUUID_ = null;
        }
        return packUUIDBuilder_;
      }
      
      // optional string message = 3;
      private java.lang.Object message_ = "";
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMessage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        message_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      void setMessage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        message_ = value;
        onChanged();
      }
      
      // optional string attributes = 4;
      private java.lang.Object attributes_ = "";
      public boolean hasAttributes() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getAttributes() {
        java.lang.Object ref = attributes_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          attributes_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAttributes(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        attributes_ = value;
        onChanged();
        return this;
      }
      public Builder clearAttributes() {
        bitField0_ = (bitField0_ & ~0x00000008);
        attributes_ = getDefaultInstance().getAttributes();
        onChanged();
        return this;
      }
      void setAttributes(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        attributes_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.xuanwu.msggate.common.protobuf.pack.PResponse)
    }
    
    static {
      defaultInstance = new PResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.xuanwu.msggate.common.protobuf.pack.PResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xuanwu_msggate_common_protobuf_pack_PResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_xuanwu_msggate_common_protobuf_pack_PResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022PackResponse.proto\022\'com.xuanwu.msggate" +
      ".common.protobuf.pack\032\020CommonItem.proto\"" +
      "\256\001\n\tPResponse\022@\n\006result\030\001 \002(\01620.com.xuan" +
      "wu.msggate.common.protobuf.pack.PResult\022" +
      ":\n\010packUUID\030\002 \001(\0132(.com.xuanwu.msggate.c" +
      "ommon.protobuf.UUID\022\017\n\007message\030\003 \001(\t\022\022\n\n" +
      "attributes\030\004 \001(\t*E\n\007PResult\022\020\n\014SUCCESS_F" +
      "LAG\020\000\022\024\n\020INNER_ERROR_FLAG\020\001\022\022\n\016DUPLICATE" +
      "_FLAG\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_xuanwu_msggate_common_protobuf_pack_PResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_xuanwu_msggate_common_protobuf_pack_PResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_xuanwu_msggate_common_protobuf_pack_PResponse_descriptor,
              new java.lang.String[] { "Result", "PackUUID", "Message", "Attributes", },
              com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse.class,
              com.xuanwu.msggate.common.protobuf.pack.PackResponse.PResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.xuanwu.msggate.common.protobuf.CommonItem.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
