// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MORequest.proto

package com.xuanwu.msggate.common.protobuf.mo;

public final class MORequest {
  private MORequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ORequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .com.xuanwu.msggate.common.protobuf.OMsgType type = 1;
    boolean hasType();
    com.xuanwu.msggate.common.protobuf.CommonItem.OMsgType getType();
    
    // required .com.xuanwu.msggate.common.protobuf.UUID uuid = 2;
    boolean hasUuid();
    com.xuanwu.msggate.common.protobuf.CommonItem.UUID getUuid();
    com.xuanwu.msggate.common.protobuf.CommonItem.UUIDOrBuilder getUuidOrBuilder();
    
    // optional string batchID = 3;
    boolean hasBatchID();
    String getBatchID();
    
    // optional bytes data = 4;
    boolean hasData();
    com.google.protobuf.ByteString getData();
    
    // optional .com.xuanwu.msggate.common.protobuf.Account user = 5;
    boolean hasUser();
    com.xuanwu.msggate.common.protobuf.CommonItem.Account getUser();
    com.xuanwu.msggate.common.protobuf.CommonItem.AccountOrBuilder getUserOrBuilder();
    
    // optional string newPwd = 6;
    boolean hasNewPwd();
    String getNewPwd();
    
    // optional int32 days = 7;
    boolean hasDays();
    int getDays();
    
    // optional int32 pageIndex = 8;
    boolean hasPageIndex();
    int getPageIndex();
    
    // optional int32 pageSize = 9;
    boolean hasPageSize();
    int getPageSize();
    
    // optional string phone = 10;
    boolean hasPhone();
    String getPhone();
    
    // optional bool isSimple = 11;
    boolean hasIsSimple();
    boolean getIsSimple();
    
    // optional string attributes = 12;
    boolean hasAttributes();
    String getAttributes();
  }
  public static final class ORequest extends
      com.google.protobuf.GeneratedMessage
      implements ORequestOrBuilder {
    // Use ORequest.newBuilder() to construct.
    private ORequest(Builder builder) {
      super(builder);
    }
    private ORequest(boolean noInit) {}
    
    private static final ORequest defaultInstance;
    public static ORequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public ORequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xuanwu.msggate.common.protobuf.mo.MORequest.internal_static_com_xuanwu_msggate_common_protobuf_mo_ORequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xuanwu.msggate.common.protobuf.mo.MORequest.internal_static_com_xuanwu_msggate_common_protobuf_mo_ORequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .com.xuanwu.msggate.common.protobuf.OMsgType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.xuanwu.msggate.common.protobuf.CommonItem.OMsgType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.xuanwu.msggate.common.protobuf.CommonItem.OMsgType getType() {
      return type_;
    }
    
    // required .com.xuanwu.msggate.common.protobuf.UUID uuid = 2;
    public static final int UUID_FIELD_NUMBER = 2;
    private com.xuanwu.msggate.common.protobuf.CommonItem.UUID uuid_;
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.xuanwu.msggate.common.protobuf.CommonItem.UUID getUuid() {
      return uuid_;
    }
    public com.xuanwu.msggate.common.protobuf.CommonItem.UUIDOrBuilder getUuidOrBuilder() {
      return uuid_;
    }
    
    // optional string batchID = 3;
    public static final int BATCHID_FIELD_NUMBER = 3;
    private java.lang.Object batchID_;
    public boolean hasBatchID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getBatchID() {
      java.lang.Object ref = batchID_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          batchID_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBatchIDBytes() {
      java.lang.Object ref = batchID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        batchID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes data = 4;
    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    
    // optional .com.xuanwu.msggate.common.protobuf.Account user = 5;
    public static final int USER_FIELD_NUMBER = 5;
    private com.xuanwu.msggate.common.protobuf.CommonItem.Account user_;
    public boolean hasUser() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public com.xuanwu.msggate.common.protobuf.CommonItem.Account getUser() {
      return user_;
    }
    public com.xuanwu.msggate.common.protobuf.CommonItem.AccountOrBuilder getUserOrBuilder() {
      return user_;
    }
    
    // optional string newPwd = 6;
    public static final int NEWPWD_FIELD_NUMBER = 6;
    private java.lang.Object newPwd_;
    public boolean hasNewPwd() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getNewPwd() {
      java.lang.Object ref = newPwd_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          newPwd_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNewPwdBytes() {
      java.lang.Object ref = newPwd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        newPwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 days = 7;
    public static final int DAYS_FIELD_NUMBER = 7;
    private int days_;
    public boolean hasDays() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getDays() {
      return days_;
    }
    
    // optional int32 pageIndex = 8;
    public static final int PAGEINDEX_FIELD_NUMBER = 8;
    private int pageIndex_;
    public boolean hasPageIndex() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getPageIndex() {
      return pageIndex_;
    }
    
    // optional int32 pageSize = 9;
    public static final int PAGESIZE_FIELD_NUMBER = 9;
    private int pageSize_;
    public boolean hasPageSize() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public int getPageSize() {
      return pageSize_;
    }
    
    // optional string phone = 10;
    public static final int PHONE_FIELD_NUMBER = 10;
    private java.lang.Object phone_;
    public boolean hasPhone() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          phone_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool isSimple = 11;
    public static final int ISSIMPLE_FIELD_NUMBER = 11;
    private boolean isSimple_;
    public boolean hasIsSimple() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public boolean getIsSimple() {
      return isSimple_;
    }
    
    // optional string attributes = 12;
    public static final int ATTRIBUTES_FIELD_NUMBER = 12;
    private java.lang.Object attributes_;
    public boolean hasAttributes() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public String getAttributes() {
      java.lang.Object ref = attributes_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          attributes_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAttributesBytes() {
      java.lang.Object ref = attributes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        attributes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      type_ = com.xuanwu.msggate.common.protobuf.CommonItem.OMsgType.LOGIN;
      uuid_ = com.xuanwu.msggate.common.protobuf.CommonItem.UUID.getDefaultInstance();
      batchID_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
      user_ = com.xuanwu.msggate.common.protobuf.CommonItem.Account.getDefaultInstance();
      newPwd_ = "";
      days_ = 0;
      pageIndex_ = 0;
      pageSize_ = 0;
      phone_ = "";
      isSimple_ = false;
      attributes_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getUuid().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasUser()) {
        if (!getUser().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, uuid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getBatchIDBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, data_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, user_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getNewPwdBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, days_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, pageIndex_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, pageSize_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getPhoneBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBool(11, isSimple_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getAttributesBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, uuid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getBatchIDBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, user_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getNewPwdBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, days_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, pageIndex_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, pageSize_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getPhoneBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(11, isSimple_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getAttributesBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xuanwu.msggate.common.protobuf.mo.MORequest.internal_static_com_xuanwu_msggate_common_protobuf_mo_ORequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xuanwu.msggate.common.protobuf.mo.MORequest.internal_static_com_xuanwu_msggate_common_protobuf_mo_ORequest_fieldAccessorTable;
      }
      
      // Construct using com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUuidFieldBuilder();
          getUserFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = com.xuanwu.msggate.common.protobuf.CommonItem.OMsgType.LOGIN;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (uuidBuilder_ == null) {
          uuid_ = com.xuanwu.msggate.common.protobuf.CommonItem.UUID.getDefaultInstance();
        } else {
          uuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        batchID_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (userBuilder_ == null) {
          user_ = com.xuanwu.msggate.common.protobuf.CommonItem.Account.getDefaultInstance();
        } else {
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        newPwd_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        days_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        pageIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        pageSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        phone_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        isSimple_ = false;
        bitField0_ = (bitField0_ & ~0x00000400);
        attributes_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest.getDescriptor();
      }
      
      public com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest getDefaultInstanceForType() {
        return com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest.getDefaultInstance();
      }
      
      public com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest build() {
        com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest buildPartial() {
        com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest result = new com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (uuidBuilder_ == null) {
          result.uuid_ = uuid_;
        } else {
          result.uuid_ = uuidBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.batchID_ = batchID_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.newPwd_ = newPwd_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.days_ = days_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.pageIndex_ = pageIndex_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.pageSize_ = pageSize_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.phone_ = phone_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.isSimple_ = isSimple_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.attributes_ = attributes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest) {
          return mergeFrom((com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest other) {
        if (other == com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasUuid()) {
          mergeUuid(other.getUuid());
        }
        if (other.hasBatchID()) {
          setBatchID(other.getBatchID());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        if (other.hasNewPwd()) {
          setNewPwd(other.getNewPwd());
        }
        if (other.hasDays()) {
          setDays(other.getDays());
        }
        if (other.hasPageIndex()) {
          setPageIndex(other.getPageIndex());
        }
        if (other.hasPageSize()) {
          setPageSize(other.getPageSize());
        }
        if (other.hasPhone()) {
          setPhone(other.getPhone());
        }
        if (other.hasIsSimple()) {
          setIsSimple(other.getIsSimple());
        }
        if (other.hasAttributes()) {
          setAttributes(other.getAttributes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasUuid()) {
          
          return false;
        }
        if (!getUuid().isInitialized()) {
          
          return false;
        }
        if (hasUser()) {
          if (!getUser().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.xuanwu.msggate.common.protobuf.CommonItem.OMsgType value = com.xuanwu.msggate.common.protobuf.CommonItem.OMsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              com.xuanwu.msggate.common.protobuf.CommonItem.UUID.Builder subBuilder = com.xuanwu.msggate.common.protobuf.CommonItem.UUID.newBuilder();
              if (hasUuid()) {
                subBuilder.mergeFrom(getUuid());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setUuid(subBuilder.buildPartial());
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              batchID_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              data_ = input.readBytes();
              break;
            }
            case 42: {
              com.xuanwu.msggate.common.protobuf.CommonItem.Account.Builder subBuilder = com.xuanwu.msggate.common.protobuf.CommonItem.Account.newBuilder();
              if (hasUser()) {
                subBuilder.mergeFrom(getUser());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setUser(subBuilder.buildPartial());
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              newPwd_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              days_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              pageIndex_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              pageSize_ = input.readInt32();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              phone_ = input.readBytes();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              isSimple_ = input.readBool();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000800;
              attributes_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .com.xuanwu.msggate.common.protobuf.OMsgType type = 1;
      private com.xuanwu.msggate.common.protobuf.CommonItem.OMsgType type_ = com.xuanwu.msggate.common.protobuf.CommonItem.OMsgType.LOGIN;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.OMsgType getType() {
        return type_;
      }
      public Builder setType(com.xuanwu.msggate.common.protobuf.CommonItem.OMsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.xuanwu.msggate.common.protobuf.CommonItem.OMsgType.LOGIN;
        onChanged();
        return this;
      }
      
      // required .com.xuanwu.msggate.common.protobuf.UUID uuid = 2;
      private com.xuanwu.msggate.common.protobuf.CommonItem.UUID uuid_ = com.xuanwu.msggate.common.protobuf.CommonItem.UUID.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.xuanwu.msggate.common.protobuf.CommonItem.UUID, com.xuanwu.msggate.common.protobuf.CommonItem.UUID.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.UUIDOrBuilder> uuidBuilder_;
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.UUID getUuid() {
        if (uuidBuilder_ == null) {
          return uuid_;
        } else {
          return uuidBuilder_.getMessage();
        }
      }
      public Builder setUuid(com.xuanwu.msggate.common.protobuf.CommonItem.UUID value) {
        if (uuidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          uuid_ = value;
          onChanged();
        } else {
          uuidBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setUuid(
          com.xuanwu.msggate.common.protobuf.CommonItem.UUID.Builder builderForValue) {
        if (uuidBuilder_ == null) {
          uuid_ = builderForValue.build();
          onChanged();
        } else {
          uuidBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeUuid(com.xuanwu.msggate.common.protobuf.CommonItem.UUID value) {
        if (uuidBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              uuid_ != com.xuanwu.msggate.common.protobuf.CommonItem.UUID.getDefaultInstance()) {
            uuid_ =
              com.xuanwu.msggate.common.protobuf.CommonItem.UUID.newBuilder(uuid_).mergeFrom(value).buildPartial();
          } else {
            uuid_ = value;
          }
          onChanged();
        } else {
          uuidBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearUuid() {
        if (uuidBuilder_ == null) {
          uuid_ = com.xuanwu.msggate.common.protobuf.CommonItem.UUID.getDefaultInstance();
          onChanged();
        } else {
          uuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.UUID.Builder getUuidBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getUuidFieldBuilder().getBuilder();
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.UUIDOrBuilder getUuidOrBuilder() {
        if (uuidBuilder_ != null) {
          return uuidBuilder_.getMessageOrBuilder();
        } else {
          return uuid_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.xuanwu.msggate.common.protobuf.CommonItem.UUID, com.xuanwu.msggate.common.protobuf.CommonItem.UUID.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.UUIDOrBuilder> 
          getUuidFieldBuilder() {
        if (uuidBuilder_ == null) {
          uuidBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.xuanwu.msggate.common.protobuf.CommonItem.UUID, com.xuanwu.msggate.common.protobuf.CommonItem.UUID.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.UUIDOrBuilder>(
                  uuid_,
                  getParentForChildren(),
                  isClean());
          uuid_ = null;
        }
        return uuidBuilder_;
      }
      
      // optional string batchID = 3;
      private java.lang.Object batchID_ = "";
      public boolean hasBatchID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getBatchID() {
        java.lang.Object ref = batchID_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          batchID_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBatchID(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        batchID_ = value;
        onChanged();
        return this;
      }
      public Builder clearBatchID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        batchID_ = getDefaultInstance().getBatchID();
        onChanged();
        return this;
      }
      void setBatchID(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        batchID_ = value;
        onChanged();
      }
      
      // optional bytes data = 4;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      
      // optional .com.xuanwu.msggate.common.protobuf.Account user = 5;
      private com.xuanwu.msggate.common.protobuf.CommonItem.Account user_ = com.xuanwu.msggate.common.protobuf.CommonItem.Account.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.xuanwu.msggate.common.protobuf.CommonItem.Account, com.xuanwu.msggate.common.protobuf.CommonItem.Account.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.AccountOrBuilder> userBuilder_;
      public boolean hasUser() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.Account getUser() {
        if (userBuilder_ == null) {
          return user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      public Builder setUser(com.xuanwu.msggate.common.protobuf.CommonItem.Account value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder setUser(
          com.xuanwu.msggate.common.protobuf.CommonItem.Account.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder mergeUser(com.xuanwu.msggate.common.protobuf.CommonItem.Account value) {
        if (userBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              user_ != com.xuanwu.msggate.common.protobuf.CommonItem.Account.getDefaultInstance()) {
            user_ =
              com.xuanwu.msggate.common.protobuf.CommonItem.Account.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = com.xuanwu.msggate.common.protobuf.CommonItem.Account.getDefaultInstance();
          onChanged();
        } else {
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.Account.Builder getUserBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      public com.xuanwu.msggate.common.protobuf.CommonItem.AccountOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.xuanwu.msggate.common.protobuf.CommonItem.Account, com.xuanwu.msggate.common.protobuf.CommonItem.Account.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.AccountOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.xuanwu.msggate.common.protobuf.CommonItem.Account, com.xuanwu.msggate.common.protobuf.CommonItem.Account.Builder, com.xuanwu.msggate.common.protobuf.CommonItem.AccountOrBuilder>(
                  user_,
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }
      
      // optional string newPwd = 6;
      private java.lang.Object newPwd_ = "";
      public boolean hasNewPwd() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getNewPwd() {
        java.lang.Object ref = newPwd_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          newPwd_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNewPwd(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        newPwd_ = value;
        onChanged();
        return this;
      }
      public Builder clearNewPwd() {
        bitField0_ = (bitField0_ & ~0x00000020);
        newPwd_ = getDefaultInstance().getNewPwd();
        onChanged();
        return this;
      }
      void setNewPwd(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        newPwd_ = value;
        onChanged();
      }
      
      // optional int32 days = 7;
      private int days_ ;
      public boolean hasDays() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getDays() {
        return days_;
      }
      public Builder setDays(int value) {
        bitField0_ |= 0x00000040;
        days_ = value;
        onChanged();
        return this;
      }
      public Builder clearDays() {
        bitField0_ = (bitField0_ & ~0x00000040);
        days_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 pageIndex = 8;
      private int pageIndex_ ;
      public boolean hasPageIndex() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public int getPageIndex() {
        return pageIndex_;
      }
      public Builder setPageIndex(int value) {
        bitField0_ |= 0x00000080;
        pageIndex_ = value;
        onChanged();
        return this;
      }
      public Builder clearPageIndex() {
        bitField0_ = (bitField0_ & ~0x00000080);
        pageIndex_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 pageSize = 9;
      private int pageSize_ ;
      public boolean hasPageSize() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public int getPageSize() {
        return pageSize_;
      }
      public Builder setPageSize(int value) {
        bitField0_ |= 0x00000100;
        pageSize_ = value;
        onChanged();
        return this;
      }
      public Builder clearPageSize() {
        bitField0_ = (bitField0_ & ~0x00000100);
        pageSize_ = 0;
        onChanged();
        return this;
      }
      
      // optional string phone = 10;
      private java.lang.Object phone_ = "";
      public boolean hasPhone() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPhone(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        phone_ = value;
        onChanged();
        return this;
      }
      public Builder clearPhone() {
        bitField0_ = (bitField0_ & ~0x00000200);
        phone_ = getDefaultInstance().getPhone();
        onChanged();
        return this;
      }
      void setPhone(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        phone_ = value;
        onChanged();
      }
      
      // optional bool isSimple = 11;
      private boolean isSimple_ ;
      public boolean hasIsSimple() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public boolean getIsSimple() {
        return isSimple_;
      }
      public Builder setIsSimple(boolean value) {
        bitField0_ |= 0x00000400;
        isSimple_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsSimple() {
        bitField0_ = (bitField0_ & ~0x00000400);
        isSimple_ = false;
        onChanged();
        return this;
      }
      
      // optional string attributes = 12;
      private java.lang.Object attributes_ = "";
      public boolean hasAttributes() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public String getAttributes() {
        java.lang.Object ref = attributes_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          attributes_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAttributes(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        attributes_ = value;
        onChanged();
        return this;
      }
      public Builder clearAttributes() {
        bitField0_ = (bitField0_ & ~0x00000800);
        attributes_ = getDefaultInstance().getAttributes();
        onChanged();
        return this;
      }
      void setAttributes(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000800;
        attributes_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.xuanwu.msggate.common.protobuf.mo.ORequest)
    }
    
    static {
      defaultInstance = new ORequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.xuanwu.msggate.common.protobuf.mo.ORequest)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xuanwu_msggate_common_protobuf_mo_ORequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_xuanwu_msggate_common_protobuf_mo_ORequest_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017MORequest.proto\022%com.xuanwu.msggate.co" +
      "mmon.protobuf.mo\032\020CommonItem.proto\"\320\002\n\010O" +
      "Request\022:\n\004type\030\001 \002(\0162,.com.xuanwu.msgga" +
      "te.common.protobuf.OMsgType\0226\n\004uuid\030\002 \002(" +
      "\0132(.com.xuanwu.msggate.common.protobuf.U" +
      "UID\022\017\n\007batchID\030\003 \001(\t\022\014\n\004data\030\004 \001(\014\0229\n\004us" +
      "er\030\005 \001(\0132+.com.xuanwu.msggate.common.pro" +
      "tobuf.Account\022\016\n\006newPwd\030\006 \001(\t\022\014\n\004days\030\007 " +
      "\001(\005\022\021\n\tpageIndex\030\010 \001(\005\022\020\n\010pageSize\030\t \001(\005" +
      "\022\r\n\005phone\030\n \001(\t\022\020\n\010isSimple\030\013 \001(\010\022\022\n\natt",
      "ributes\030\014 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_xuanwu_msggate_common_protobuf_mo_ORequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_xuanwu_msggate_common_protobuf_mo_ORequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_xuanwu_msggate_common_protobuf_mo_ORequest_descriptor,
              new java.lang.String[] { "Type", "Uuid", "BatchID", "Data", "User", "NewPwd", "Days", "PageIndex", "PageSize", "Phone", "IsSimple", "Attributes", },
              com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest.class,
              com.xuanwu.msggate.common.protobuf.mo.MORequest.ORequest.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.xuanwu.msggate.common.protobuf.CommonItem.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
