spring:
  application:
    name: api-gateway
  mvc:
    favicon:
      enabled: false
server:
  port: 5555
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:1111/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
zuul:
  routes:
    mos-auth:
      path: /mos/service/login/**
      serviceId: mos-auth
      sensitiveHeaders:
      stripPrefix: false
    mos-service:
      path: /mos/service/**
      serviceId: mos
      sensitiveHeaders:
      stripPrefix: false
  #add-host-header: true
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false
hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
base64:
  key_str_config: mos5.0FrontKit
  key_str_ks: REXlIBoScafdJhtkGpeqHKiubMmWOsArQgUYZFVDTvynwjxzLCNP

gateway:
  auth_limit_time: 5
  auth_white_list: /mos/service/login,/mos/service/common #/web-backend/login
  ratelimit_qps: 5000
logging:
  level:
    com.xuanwu: debug
    #root: debug

